server:
  port: 7001
eureka:
  instance:
    hostname: www.eureka7001.com
    instance-id: eureka-server-7001
  client:
    serviceUrl:
      defaultZone: http://www.eureka7001.com:7001/eureka/, http://www.eureka7002.com:7002/eureka/, http://www.eureka7003.com:7003/eureka/
spring:
  application:
    name: eureka-server
---
server:
  port: 7002
eureka:
  instance:
    hostname: www.eureka7002.com
    instance-id: eureka-server-7002
  client:
    serviceUrl:
      defaultZone: http://www.eureka7002.com:7002/eureka/
spring:
  profiles：dev
  application:
    name: eureka-server

